POST http://localhost:3003/api/boards
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1la2ludG93biIsImlkIjoiNjUzNjI4Y2UxZDFiN2ZkNDZjMjRiZTEwIiwiaWF0IjoxNjk4MjM2Njg3fQ.aa4-J4mEgPKNej67Qzbc4GMMoPl1OSw4PkERAzDecUg

{
    "name": "Chula"
}

###
GET http://localhost:3003/api/boards

###
POST http://localhost:3003/api/boards
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1lbXVrIiwiaWQiOiI2NTM5MTY5NzY1M2Q4NDNmZTBiMGViZmEiLCJpYXQiOjE2OTgyNDAxNjV9.-TrrmYXAEPIW0WqfN2wU5z1P3Zv8PL27zzMkjd85Lfs

###
DELETE http://localhost:3003/api/boards/65390c42ed4a497b7f2215cc
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1la2ludG93biIsImlkIjoiNjUzNjI4Y2UxZDFiN2ZkNDZjMjRiZTEwIiwiaWF0IjoxNjk4MjQwNDkwfQ.x-WsGtXI1LGVpzzQgFlPGCmyKnfIPQPyaFn4SxmdkSE