POST http://localhost:3003/api/users
content-type: application/json

{
    "username": "mekindie",
    "name": "Maekin Namwong",
    "password": "Testpassword1"
}

###
POST http://localhost:3003/api/users
content-type: application/json

{
    "username": "memuk",
    "password": "root1234"
}

###
GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/login
content-type: application/json

{
    "username": "mekindie",
    "password": "Testpassword1"
}

###
POST http://localhost:3003/api/login
content-type: application/json

{
    "username": "memuk",
    "password": "root1234"
}

