POST http://localhost:3003/api/tasks
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1la2ludG93biIsImlkIjoiNjUzOTVlNzUyZDdlOWEwMjMxMjdhYWVlIiwiaWF0IjoxNjk4MjU4NTc3fQ.ZjErnmoA37iqt83McVH1rDcdFcjdQ02V6JjO52-0DOY

{
    "board": "65395f752d7e9a023127ab0f",
    "title": "First"
}